pivnet_token: <replace me>     #https://network.pivotal.io/users/dashboard/edit-profile
maven_url: <replace me>        #curl -v -u admin:admin123 --upload-file pom.xml http://localhost:8081/repository/maven-releases/org/foo/1.0/foo-1.0.pom
username: <replace me>         #username for repo
password: <replace me>         #password for repo
