resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: autoscaler
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: pcf-app-autoscaler
    product_version: ^2\.0\..*

jobs:
- name: upload-plugin
  plan:
  - get: autoscaler
    trigger: true
    params:
      globs: ["autoscaler-for-pcf*"]
  - task: upload
    config:
      inputs:
      - name: autoscaler
      platform: linux
      params:
        username: ((username))
        password: ((password))
        maven_url: ((maven_url))
      image_resource:
        type: docker-image
        source: {repository: brianbyers/ubuntu-curl}
      run:
        path: bash
        args:
        - "-c"
        - |
          set -eux
          cd autoscaler
          files=`find . -name "autoscaler-for-pcf*"`
          for f in $files
          do
            filename=$(basename $f)
            curl -v -u $username:$password --upload-file $filename $maven_url/$filename
          done
