resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: autoscaler-cli
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: pcf-app-autoscaler
    product_version: ^2\.0\..*

jobs:
- name: upload-plugin
  plan:
  - get: autoscaler-cli
    trigger: true
    params:
      globs: ["autoscaler-for-pcf*"]
  - task: upload
    config:
      inputs:
        - name: autoscaler-cli
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: export
        args:
        - -v
        - -u
        - ((user-pass))
        - --upload-file
        


#curl -v -u admin:admin123 --upload-file pom.xml http://localhost:8081/repository/maven-releases/org/foo/1.0/foo-1.0.pom
